### ISSUE TITLE
Run Lerna with CI mode to speed up install times

### ISSUE THREAD

**Issue by RobertWSaunders** [qhacks/qhacks-dashboard#156]
## Summary

#155 Updates Lerna to a version where it runs `npm ci` instead of `npm install` in CI environments to speed up install times. Because we don't have a `package-lock.json` in our project it fails as it is required for `npm ci`. Should we add this?

### Motivation

I think the motivation for this change is to decrease install times in CI and as a result speed up our build times.

**Comment by joeytepp** [comment]
This might be worthwhile since we've been seeing some timeout errors on CI, really hate intermittently failing tests and it could get worse as we add more dependencies. Will also help us avoid issues like we saw with mongoose, cant rely solely on unit tests for stuff like that. Will make a PR for this soon

**Comment by RobertWSaunders** [comment]
Sounds good, thanks for picking this one up!

**Comment by joeytepp** [comment]
Closing this for now due to complications with hoisted packages. May be worth doing something about this in the future if we see more timeouts during the `bootstrap process`, which could also be done by updating our CircleCI config. As of now, not worth sacrificing all the benefits of hoisting for a few seconds off the install time
