### ISSUE TITLE
Add reviews to Application type in GraphQL

### ISSUE THREAD

**Issue by joeytepp** [qhacks/qhacks-dashboard#231]
## Summary
Applications need to support reviews, as we will soon be reviewing the applications that come in

Brief explanation of the feature.
The `Application` type should have a `reviews` field with an array of type `ApplicationReview`.

### Basic Example

Schema:
```graphql
type Application {
  ...
  reviews: [ApplicationReview!]!
}

type ApplicationReview {
  performedBy: Admin!
  reviewedAt: Date!
  score: Integer!   
}
```

A basic query:
```graphql
application(id: $id) {
  reviews: {
    reviewedAt
    score
    performedBy: {
       firstName
       lastName
       email
    }
  }
} 
```

### Motivation
To add more functionality to the API

Why are we doing this? What use cases does it support? What is the expected outcome?
Allows admins to perform reviews and see the reviews of applications

**Comment by RobertWSaunders** [comment]
When making a query on a list you don't use square brackets FYI.

**Comment by RobertWSaunders** [comment]
This design looks good to me! What are the queries and mutations related to application reviews?

**Comment by joeytepp** [comment]
This is what I have for mutations:

```graphql
extend type MutationRoot {
  applicationReviewCreate(
    input: ApplicationReviewInput!
  ): ApplicationReviewCreatePayload!
}

input ApplicationReviewInput {
  """
  The score awarded in the review.
  """
  score: Int!
  """
  The slug of the event for which the review is being submitted.
  """
  eventSlug: String!
  """
  The email of the user for whom the review is being submitted.
  """
  userEmail: String!
}

type ApplicationReviewCreatePayload {
  applicationReview: ApplicationReview
}
```

**Comment by joeytepp** [comment]
For queries, currently I just have an `applications` query that returns all the applications, thinking now that it should maybe be a connection off of the `Event` type with cursor based pagination. That would also prevent the need for including a user email and event slug in the input, could just provide an id from the cursor

**Comment by RobertWSaunders** [comment]
So, I think it would be better to follow this for the mutation:

```graphql
extend type MutationRoot {
  applicationReviewCreate(
    applicationID: ID!, 
    input: ApplicationReviewInput!
  ): ApplicationReviewCreatePayload!
}

input ApplicationReviewInput {
  """
  The score awarded in the review.
  """
  score: Int!
}

type ApplicationReviewCreatePayload {
  applicationReview: ApplicationReview
}
```

Key changes:

- Remove identifying elements from the input type.
  - We want to reuse our input types for both create and update. By having identifying elements (`id`, `userEmail`, `eventSlug`) in the input type that might be good for update mutations but not good for create mutations. 
- Use `applicationId` argument instead of `userEmail` and `eventSlug`. 
  - The application is what we are reviewing, requiring the `userEmail` and the `eventSlug` to identify the application is weird. You would only ever review an application that you know about (i.e. have the identifier for).

**Comment by RobertWSaunders** [comment]
For creating mailing list subscribers we provide developers the luxury to use a slug combination or strictly the mailing list identifier. When ever we want to not use the conventional way of identifying items (i.e. use slugs) we must also provide the ability to use identifiers. See below:

```graphql

extend type QueryRoot {
 mailingListSubscriberCreate(
    mailingListId: ID!
    input: MailingListSubscriberInput!
  ): MailingListSubscriberCreatePayload!

  mailingListSubscriberCreateBySlug(
    eventSlug: String!
    mailingListSlug: String!
    input: MailingListSubscriberInput!
  ): MailingListSubscriberCreatePayload!
}
```

Notice how are able to reuse `MailingListSubscriberInput` because the identifying fields are abstracted out.

**Comment by joeytepp** [comment]
Yea makes sense, we'll need to update the schema to return an id for the `Application` type, otherwise it will never be exposed to the client, so I will make that change here as well

**Comment by RobertWSaunders** [comment]
Yep that will be needed. Eventually we will be making use of the `Node` interface which `Application` will implement. For now you can just add the `id` field to the `Application` type! 👍
